### ISSUE TITLE
Break down the main equipment dashboard into React components

### ISSUE THREAD

**Issue by duci9y** [JumboCode/TUTV#15]
This is a rough sketch of our main dashboard:

<img width="822" alt="2 Main Dashboard" src="https://user-images.githubusercontent.com/8692416/66863592-5cd77100-ef61-11e9-9687-a247c67db67e.png">

Consider what else may be required on this page as a laid out React component, eg. a header/footer? Feel free to consult @emai-lai if in doubt. Then, using a simple app like Preview (on Mac) or Paint (Windows), draw rectangles around visual elements that will probably need to be components.

I am thinking a sidebar vs. main content component division could be useful, just a suggestion.

1. Create an issue specifically for the calendar component tree, which you probably don't need to break down too much. Assign this to @kmoran04, who will decide whether to use a third party component or build our own from scratch.

2. Break down the rest of the page into slightly more detailed component trees, but not too much. Create an issue for this containing your updated sketch and assign it to @erenaci and @isabellau. They will implement basic scaffolding for those component trees in code.

Note: These are still rough sketches. Don't worry about being 'wrong' about something.

**Comment by kmoran04** [comment]
Do the red crossed out tabs mean I shouldn't create a component for them?

**Comment by duci9y** [comment]
Yup, that’s correct.

**Comment by kmoran04** [comment]
Also these are just React functional components, not styled components, correct?

**Comment by duci9y** [comment]
Yup! No CSS styles yet. Or did you mean something else by “styled”?

**Comment by kmoran04** [comment]
styled-components is a React package that lets you treat a styled element like a component, so like <IconTitle> text </IconTitle> would be just text with added styling and it isn't a **functional** component, but it is a component technically

**Comment by duci9y** [comment]
Ah. Looked into it. It does not look suitable for our project, so let’s stick to functional components. 

>
