### ISSUE TITLE
Complete Equipment Browser page

### ISSUE THREAD

**Issue by emai-lai** [JumboCode/TUTV#34]
<img width="674" alt="Screen Shot 2019-11-11 at 5 34 16 PM 2" src="https://user-images.githubusercontent.com/46794504/68626681-e79c8480-04a9-11ea-9544-ec6eb5918da8.png">

This issue depends on #33, which is the Equipment Browser page.
Complete the page by making the equipment browser with tab functionality. Use Luke's fake database to populate the browser. Make sure the equipment grid is a reusable component, as we will also use this layout on other pages (ex. #35)

Also leave room on the right for where the selected items will be displayed.

**Comment by duci9y** [comment]
Closed by #44.
