### ISSUE TITLE
Create Checkout Request Summary page

### ISSUE THREAD

**Issue by emai-lai** [JumboCode/TUTV#35]
<img width="674" alt="Screen Shot 2019-11-11 at 5 31 36 PM" src="https://user-images.githubusercontent.com/46794504/68626343-2f6edc00-04a9-11ea-91f8-f93065d5a55e.png">

Break the Request Summary page down into React components. Use the same equipment grid component from the Equipment Browser (#34).  

Also use the button component that we've already created -- make the Back button return to the Equipment Browser page (#34), and make the Confirm Request button go to the Request Confirmation page (#36). The checkout date/time can be static text for now.

**Comment by duci9y** [comment]
Closed by #47.
