### ISSUE TITLE
Updating Equipment Browser Page from tabs to collapsible boxes

### ISSUE THREAD

**Issue by emai-lai** [JumboCode/TUTV#57]
![Equipment Browser 3](https://user-images.githubusercontent.com/46794504/75123459-8e7de880-5675-11ea-903d-90ef7410d274.png)

We will be changing the structure of this browser from tabs (created in issue #34) to collapsible boxes as shown above. Tab categories will include "Camera, Audio, Lighting, Miscellaneous, etc."
 
You can also add buttons to each equipment item that will allow the user to instantly add it to their cart.

Don't worry yet about the spacing or number of items per row.

**Comment by Frama-99** [comment]
Closed through https://github.com/JumboCode/TUTV/pull/141. Opted for both tabs and sections to accommodate for categories (e.g. Camera) as well as types (e.g. Camera -> Tripod)
