### ISSUE TITLE
Create generic pop-up component

### ISSUE THREAD

**Issue by duci9y** [JumboCode/TUTV#74]
Create a generic pop-up component. #60 and #72 depend on this to be in `/components`. @emai-lai if you can provide a mockup for an empty popup and attach it here that will be super useful!

Here's some props I think it will need: width/height (optional, it should fit to content otherwise), close button handler (optional), completion handler (optional), content (which can just be children, thoughts?).

**Comment by emai-lai** [comment]
![Pop-up Modal](https://user-images.githubusercontent.com/46794504/76173741-61066400-6178-11ea-9e88-0ec7e91d4fe8.png)

Generic modal/pop-up component

Corner radius = 40px
Distance of X icon from edges = 24 px
