### ISSUE TITLE
Visually refine Equipment Browser

### ISSUE THREAD

**Issue by emai-lai** [JumboCode/TUTV#96]
![Equipment Browser](https://user-images.githubusercontent.com/46794504/79281893-bde4f080-7e81-11ea-9654-c532f4fe5890.png)
This issue is to be completed after issue #57 

Visually refine the wireframe to more closely resemble this mockup. Specific things to note:
- Pull similar structure of the "Project Time, Checkout Time, and Return Time" top bar from the Member Dashboard page
- Make sure to use the correct iconography for the up and down arrows (from Feather icons set #80)
- Establish the default/empty equipment cart (right). Mockup with populated equipment cart will be a [separate ticket](https://github.com/JumboCode/TUTV/issues/97).
- See [style sheet](https://www.figma.com/file/Po7ZSOM7W6ZRVJQFXlilIC/TUTV-JumboCode?node-id=355%3A1693) for colors, fonts, etc.

See Figma screen for dimensions [here](https://www.figma.com/file/Po7ZSOM7W6ZRVJQFXlilIC/TUTV-JumboCode?node-id=234%3A0).

**Comment by XeniaRud** [comment]
Closed with pull request #99
