### ISSUE TITLE
Visually refine Equipment Cart (in Equipment Browser page)

### ISSUE THREAD

**Issue by emai-lai** [JumboCode/TUTV#97]
![Equipment Browser with Non-empty Cart](https://user-images.githubusercontent.com/46794504/79283307-76606380-7e85-11ea-99d9-88b935d99d08.png)

Only focus on the visual refinements to the Equipment Cart (on the right-hand side). When the cart is non-empty, it will display the items that the user has selected and added to the cart. Each item element will include its **picture**, **name**, and **quantity**.

Emphasis on consistent spacing between items and making sure the text shrinks or wraps if needed.

Try to get the scroll bar functionality to work for lists that go beyond the page.

See Figma screen for dimensions [here](https://www.figma.com/file/Po7ZSOM7W6ZRVJQFXlilIC/TUTV-JumboCode?node-id=504%3A16).

**Comment by Frama-99** [comment]
Closed through https://github.com/JumboCode/TUTV/pull/141.
